# Exported from Render on 2024-11-08T04:55:29Z
databases:
- name: my-db
  databaseName: auto_created_by_render
  user: auto_created_by_render
  plan: free
  region: your_region
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: deploy-to-render:latest
  runtime: image
  image:
    url: docker.io/your-docker-hub-username/deploy-to-render:latest
  plan: free
  envVars:
  - key: SECRET_KEY
    sync: false
  - key: S3_SECRET
    sync: false
  - key: FLASK_ENV
    sync: false
  - key: S3_KEY
    sync: false
  - key: S3_BUCKET
    sync: false
  - key: FLASK_APP
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: my-db
      property: connectionString
  region: ohio
version: "1"
