services:
  api:
    build:
      context: .
    ports:
      - 5000:5000
    develop:
      watch:
        - path: requirements.txt
          action: rebuild
        - path: ./app/
          target: /var/www/app
          action: sync
